# Generated by Django 6.0.2 on 2026-03-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='image',
            new_name='recipe_image',
        ),
    ]
